### ISSUE TITLE
Implement Persistence on Buffer Pool

### ISSUE THREAD

**Issue by ArnauPrat** [DAMA-UPC/smile#4]
The m_allocationTable in the buffer pool should be persisted in the disk at page "0" of the storage. Then the next X number of consecutive pages should be available to use in the buffer pool (note that X would depend on the page size). When X pages are allocated and the allocation table bitmap is full, another allocation table bitmap should be placed at page 1+X+1, to control the allocation of X more pages, and so on and so forth.
When closing the buffer pool or checkpointing, the allocationTable should be written back to the disk. But as I said, this can be implemented in another pull request, just make clear that his one does not implement the disk persistence.

**Comment by ferranolivera** [comment]
I plan to implement such functionality in a future pull request.

**Comment by ferranolivera** [comment]
Fixed in 8b1763a.
